### ISSUE TITLE
Probing with different datasets

### ISSUE THREAD

**Issue by violenil** [dmis-lab/BioLAMA#3]
Hi there! This work is really interesting, and so relevant to my own.
I've been creating a fact-checked dataset of 300 tweets (all COVID-19 related, biomedical themed; fact-checked using crowdsourcing) as part of my Masters thesis and would really like to probe both BERT and BioBERT, using your probe. I've constrained the dataset quite heavily, only considering 'cause' relations, and I've annotated biomedical named entities, for example:
 
`[Moderna vaccine TREATMENT] may cause [neurodegenerative disorders MEDICAL CONDITION] like [Alzheimer's MEDICAL CONDITION]`

Unfortunately, I have not linked these to puids or uuids in any database, so I am not sure I would be able to make full use of the prompt generation. Would it make sense to feed these 300 instances (with masked objects) to the `cli_demo.py` for this dataset? Would it be possible to somehow calculate an evaluation score on this? As far as I can see, the `cli_demo.py` only returns predictions, but does not do any accuracy scoring.

Any help and ideas are really appreciated. Thanks in advance, and really great work!

**Comment by mjeensung** [comment]
Hi! Thank you for your interest in our work.

If you'd like to probe with different datasets and see the accuracy, I recommend you to run `run_manual.py`.
https://github.com/dmis-lab/BioLAMA/blob/main/README.md#manual-prompt

All you need is to create `test.jsonl ` and `manual.jsonl`.
It would be helpful to download `dataset.tar.gz` and see how they look.

For `uuid`, `predicate_id`, `sub_uri`, `sub_type`, `sub_aliases`, `obj_uris`, `obj_types`, and `obj_aliases`, it's okay to put anything like empty strings or whatever.

`sub_label` and `obj_lables` are important.
For `sub_label`, put a subject (e.g., `"Moderna vaccine"` in your example).
For `obj_lables`, put objects like (e.g., `["Alzheimer's"]` in your example).

Can this help answer your question?
If you have more questions, please feel free to let me know.

**Comment by violenil** [comment]
Thanks for your answer! That's exactly what I have done. I also have synonyms in the `obj_aliases` and `sub_aliases` slot for each entry. 

I'm able to run the `run_manual.py` on my dataset. However, unfortunately, I always get the following error:
```
Traceback (most recent call last):
  File "./BioLAMA/run_manual.py", line 149, in <module>
    main()
  File "./BioLAMA/./BioLAMA/run_manual.py", line 101, in main
    result = evaluator.evaluate(
  File "./BioLAMA/BioLAMA/evaluator.py", line 116, in evaluate
    _hit = self.evaluate_preds_for_single_sample(preds=[kth_pred], golds=golds)
  File "./BioLAMA/BioLAMA/evaluator.py", line 67, in evaluate_preds_for_single_sample
    em = get_raw_score(pred, golds)
  File "./BioLAMA/BioLAMA/evaluator.py", line 34, in get_raw_score
    em = max(compute_exact(a, pred) for a in golds)
ValueError: max() arg is an empty sequence
```
I had a look at what `pred` and `golds` are in the instance where this error occurs, and pred seems to be `.` while golds is an empty list `[ ]`.

I'm not entirely sure how to solve this error. Do you have any idea? Thanks for your help in advance!

**Comment by violenil** [comment]
For interest sake, my dataset gets the following scores with bioBert as a model:
```
PID	Acc@1	Acc@5
-------------------------
UR214	2.87	6.9
UR173	0.0	4.76
```

**Comment by mjeensung** [comment]
You made it!
Thank you for sharing your use case with me.

By the way, I recommend you to make a manual prompt end with `"."`.
For example, the prompt should be like `"[X] may cause [Y]."` not like `"[X] may cause [Y]"`.
If so, the model won't predict `"."`.

I hope this also helps your project.
