### ISSUE TITLE
How to re-produce results for Biomedical Entity Search Tool (BEST)?

### ISSUE THREAD

**Issue by hguan6** [dmis-lab/BioLAMA#4]
Their website https://best.korea.ac.kr/ doesn't work.

**Comment by mjeensung** [comment]
Thank you for letting us know.
There's an issue on the server so as soon as we fix it, we'll let you know.

**Comment by jhyuklee** [comment]
You can now use BEST: http://best.korea.ac.kr/ (no https @mjeensung double check?).

**Comment by mjeensung** [comment]
Thank you for your patience.

I just uploaded the code for running the IE baseline.
https://github.com/dmis-lab/BioLAMA#ie-baseline-best

If you have any trouble when running it, please let me know :)

Thank you again!

**Comment by hguan6** [comment]
Thank you very much!
