### ISSUE TITLE
data link is not available

### ISSUE THREAD

**Issue by seasonyao** [dmis-lab/BioLAMA#5]
Hi, thank you for this good work. I just found the data link (http://nlp.dmis.korea.edu/projects/biolama/data.tar.gz) is not available. Can you help me to fix it? Thanks

**Comment by mjeensung** [comment]
Hi @seasonyao 

Thank you for reaching out to us.
Due to an issue with our file server, we uploaded the data to Google Drive instead.
Could you please try [this link](https://drive.google.com/file/d/1ZVm_4QqJ21fS5vIvUSTaMKxePhME6Nn0/view?usp=sharing)?

**Comment by seasonyao** [comment]
Thanks
