### ISSUE TITLE
triples_processed of UMLS‘s data is empty?

### ISSUE THREAD

**Issue by duolatx** [dmis-lab/BioLAMA#6]
I'm very interesting with your paper.But when I implemented your experiment,I found that triples_processed of UMLS‘s data is empty.Could you provide the dataset?

**Comment by mjeensung** [comment]
Hi, @duolatx 

Thanks for reaching out to us!
Sorry for the inconvenience, and we re-uploaded the BioLAMA datasets including the UMLS triples.
Please visit https://github.com/dmis-lab/BioLAMA/blob/main/README.md#datasets and let us know if you need any further information.

**Comment by duolatx** [comment]
Thank you very much!
